version: '3'
services:
  backend:
    build: 
      context: ./backend/nodejs_server/
      dockerfile: Dockerfile 
    container_name: ms-server-db
    restart: always 
    ports:
      - '5000:5000'
  # frontendcmployee:
  #   container_name: employee
  #   build: 
  #     context: ./frontend/db-project/
  #     dockerfile: Dockerfile 
  #   volumes:
  #     - '/app1'
  #     - '/app1/node_modules'
  #   ports:
  #     - 3001:3000
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   command: npm start
  frontendcustomer:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend/customer/
    volumes:
      - /app/node_modules
      - ./client:/app