version: '3'
services:
  backend:
    build: 
      context: ./backend/nodejs_server/
      dockerfile: Dockerfile 
    container_name: ms-server-db
    restart: always 
    ports:
      - '5000:5000'
